steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/kd-open-webui:latest .
  automapSubstitutions: true
images:
- 'europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/kd-open-webui:latest'
